spring:
  profiles: eurekaService1
server:
  port: 8888
eureka:
  instance:
    hostname: eurekaService1 # 指定该Eureka实例的主机名
    preferIpAddress: true
  client:
    serviceUrl:    #多个地址使用 , 分隔。
      defaultZone: http://eurekaService2:8887/eureka/,http://eurekaService3:8886/eureka/
