spring:
  profiles: eurekaService3
server:
  port: 8886
eureka:
  instance:
    hostname: eurekaService3 # 指定该Eureka实例的主机名
    preferIpAddress: true
  client:
    serviceUrl:    #多个地址使用 , 分隔。
      defaultZone: http://eurekaService1:8888/eureka/,http://eurekaService2:8887/eureka/