version: "3"
services:
  modulea:
    image: docker.registry.server:5000/eurekaclientdockera
    ports:
      - "8001:8001"
    networks:
      default:
        ipv4_address: 182.18.0.16
#    deploy:
#      replicas: 2
#      resources:
#        limits:
#          cpus: "2"
#          memory: 500M
#      restart_policy:
#        condition: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "10"
#  moduleb:
#    image: docker.registry.server:5000/eurekaclientdockerb
#    ports:
#      - "8002:8002"
#    deploy:
#      replicas: 3
#      resources:
#        limits:
#          cpus: "2"
#          memory: 500M
#      restart_policy:
#        condition: on-failure
#    logging:
#     options:
#       max-size: "10m"
#       max-file: "10"
networks:
  default:
    external:
      name: eureka-net
